### ISSUE TITLE
Layout para o site da Open School

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/openschoolbr.github.io#1]

**Comment by nandomoreirame** [comment]
:eyes:

**Comment by sergioandrade** [comment]
Posso ajudar o/

**Comment by larismourullo** [comment]
O que seria necessário no site? Apenas os cursos? Informações dos contribuidores? Devo desenhar um wireframe para depois implementar o layout.

**Comment by kvnol** [comment]
Pessoal, a princípio teríamos uma página institucional para divulgar as redes e nossa comunidade aqui como foi acordado em alguma issue que não encontrei, mas que já, já eu linko.

Fiz um rascunho do que eu acho que seria legal, mas mandem sugestões. Estou criando um time no Marvel App.

**Comment by kvnol** [comment]
Creio que o minimalismo, com foco no conteúdo, para essa primeira página seja essencial: https://marvelapp.com/9ac5ff4

**Comment by anony000** [comment]
Estou disposto a ajudar na contrução do site no que precisar.

**Comment by anony000** [comment]
Já ajudei no desenvolvimento do site do Training Center, e graças a eles encontrei o open school hehe

**Comment by tadeubdev** [comment]
Gostei do visual @kvnol.

**Comment by anony000** [comment]
Também curti ele.

**Comment by larismourullo** [comment]
@kvnol sim, minimalismo é tudo. Eu ainda acho que o roxo poderia estar presente em alguns detalhes do site. Amanhã (Domingo) estarei desenhando um layout e postando aqui galera.

**Comment by kvnol** [comment]
@larismourullo O roxo entraria nos detalhes (:hover), por enquanto.

**Comment by andersoonweb** [comment]
@kvnol gostei, só mudaria algumas coisinhas:

- Trabalharia com outros tons não apenas preto e branco.
- Adicionaria um bloco na home com as séries, algo tipo: um ícone, assunto e quantidades de aulas.
-  Se não me engano tem uma repositório q dá pra as pessoas pedi artigos, acharia interessante também conter alguns artigos.
 - E colocar a cara de quem está envolvido nesse projetão. Sim, na home!

Pensei algo mais robusto mesmo, com um pouco mais de informação. Sendo que, só a página curso teria uma página externa.

**Comment by kvnol** [comment]
@andersoonweb massa, tive umas ideias e vou desenhar. desenhem também! <3

**Comment by andersoonweb** [comment]
@kvnol, só fraco em prototipagem, inclusive quero ajudar hahaa.

**Comment by kvnol** [comment]
De boa, @andersoonweb, vou desenhar e vou mandando aqui. Fim de semana é correria pra mim, mas vou tentar desenhar ainda hoje.

**Comment by nandomoreirame** [comment]
@kvnol se precisar de mim só falar tbm

**Comment by kvnol** [comment]
Pessoal, subi a primeira versão para não ficarmos sem nada, mas vou ir desenhando, durante a semana, as outras telas. Para ajustes, podem ir abrindo PRs. :heart:

**Comment by larismourullo** [comment]
Galera hoje não deu, amanhã tem trabalho, mas se tudo der certo ainda essa semana sai. Fico devendo essa.

**Comment by kvnol** [comment]
Tranquilo, @larismourullo. :heart:

**Comment by khaosdoctor** [comment]
Eu acho que a gente pode concentrar isso só nas PR's tudo bem @kvnol e @larismourullo porque ai vocês já vão fazendo e mandando na PR com algumas prints e tal, ai o pessoal vai comentando :) 

Vou fechar essa aqui então 😉
