### ISSUE TITLE
Tecnologias para o site

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/openschoolbr.github.io#5]
Da mesma forma que padrões estão sendo definidos para os cursos, é interessante definirmos tecnologias para o nosso próprio site. E essa issue tratará sobre isso.

**Comment by kvnol** [comment]
### Site institucional
Creio que para nossa primeira versão de site não seja necessária algo muito potente. Imagino que Jekyll já seja bom para o front-end, por enquanto, como não teremos uma plataforma interna.

**Comment by larismourullo** [comment]
Eu acredito que jekyll também seja a opção mais prática no momento.

**Comment by muniz95** [comment]
Também optaria por Jekyll

**Comment by nandomoreirame** [comment]
Jekyll é vida ❤️

**Comment by kvnol** [comment]
Topper, então.
